### ISSUE TITLE
Tja SQL-Datei fehlt wohl ;)

### ISSUE THREAD

**Issue by Dotta4You** [anonymousnuller/pshosting#1]
Nen bissel blöd ohne SQL datei nh xD
Ohne die Funktioniert das ganze Panel nd^^

**Comment by anonymousnuller** [comment]
Wurde Hinzugefügt

**Comment by Dotta4You** [comment]
ok

**Comment by Dotta4You** [comment]
Hättest das auch sein lassen können... Lösch am besten diese Leaks, du zerstörst anderen Arbeit und erzählst sogar nicht die Wahrheit Glaub mir ich kenne die Hintergründe... Lass es einfach und wenn du wenigstens ein bisschen korrekt bist und ehre hast lösch die Leaks, wenn ich deine Sachen hätte und das leaken würde würdest du auch nicht sonderlich glücklich darauf reagieren...
